simulator:
  fps      : 30  # 60fps
  sim_step : 100 # Maximun LCP solver step

display:
  WIDTH : 1600
  HEIGHT: 1200
  unit:   0.005 # [m/pixel]

pusher:
  pusher_num      : 2
  pusher_heading  : 0
  pusher_radius   : 0.1
  pusher_distance : 0.25
  pusher_position : [0.0, -1.0]
  pusher_rotation : 0

  # pusher_num      : 3
  # pusher_heading  : 0.523598667
  # pusher_radius   : 0.1
  # pusher_distance : 0.25
  # pusher_position : [0.0, -1.0]
  # pusher_rotation : 0

  unit_v_speed    : 0.5  # [m/s]
  unit_r_speed    : 0.4  # [rad/s]


slider:
  # slider_radius   : [0.5]
  # slider_position : [[0.0, 0.1]]

  slider_radius   : [0.5, 0.3]
  slider_position : [[0.0, 0.1], [1.0, -2.0]]
