simulator:
  fps      : 60  # 60fps
  sim_step : 100 # Maximun LCP solver step

display:
  WIDTH : 1600
  HEIGHT: 1200
  unit:   0.005 # [m/pixel]

pusher:
  pusher_num      : 2
  pusher_heading  : 0
  pusher_radius   : 0.1
  pusher_distance : 0.25
  # pusher_distance : 0.6
  pusher_position : [0.0, -1.0]
  # pusher_position : [0.0, -0.5]
  # pusher_position : [-1.0, -0.3]
  pusher_rotation : 0

  # pusher_num      : 3
  # pusher_heading  : 0.523598667
  # pusher_radius   : 0.1
  # pusher_distance : 0.25
  # pusher_position : [0.0, -1.0]
  # pusher_rotation : 0

  unit_v_speed    : 0.5  # [m/s]
  unit_r_speed    : 0.4  # [rad/s]

slider:
  #q, v, radius
  circle: 
    [
      [[0.0, 0.1, 0.0], [0.0, 0.0, 0.0], 0.5],
      [[0.0, 1.0, 0.0], [0.0, 0.0, 0.0], 0.3],
      # [[1.5, 0.0, 0.0], [0.0, 0.0, 0.0], 0.1],
      # [[1.0, 1.0, 0.0], [0.0, 0.0, 0.0], 0.5],
      # [[-2.5, -1.0, 0.2], [0.0, 0.0, 0.0], 0.1],
      # [[-2.5, 1.5, 0.2], [0.0, 0.0, 0.0], 0.2],
    ]
  #q, v, a, b
  ellipse:
    [
      [[1.0, 0.0, 0.2], [0.0, 0.0, 0.0], 0.6, 0.1],
    ]
  #q, v, a, b, n
  superellipse:
    [
      [[-1.5, 0.0, -0.4], [0.0, 0.0, 0.0], 0.6, 0.1, 100],
    ]
